### ISSUE TITLE
Give public transportation recommendation

### ISSUE THREAD

**Issue by pacarole** [codeforamerica/joblint#4]
At the very basic level, we have a permanent message that encourages job posters to include info about public transportation from major metro areas.

A slight iteration would be to scan for instances of 'bus' or 'train' and only show the warning if those words are not present.

There are more complicated versions that would take location info and generate directions for the poster, but those are beyond the scope of the tool for time being.

**Comment by pacarole** [comment]
Sample text forthcoming.

**Comment by antislice** [comment]
This issue was moved to codeforamerica/posting-pro#14
