### ISSUE TITLE
Come up with prompts for job posting tool

### ISSUE THREAD

**Issue by antislice** [codeforamerica/joblint#44]
Create a set of prompts that can guide an employer to create a good/fair job positing.

Current design is side-by side boxes, basically an expansion of the existing tool, so keep this in mind.

This issue originally created by @pacarole as codeforamerica/nola-2016-fellows#55.

**Comment by antislice** [comment]
ORIGINAL COMMENT BY @antislice ([here](https://github.com/codeforamerica/nola-2016-fellows/issues/55#issuecomment-199557222))

This issue was moved to antislice/api-test#35

**Comment by skcain** [comment]
![img_6757](https://cloud.githubusercontent.com/assets/15744911/13971171/32ccd134-f04b-11e5-872d-c5d54f1a3a09.JPG)

**Comment by skcain** [comment]
- Company Name
- Company Description
- Employment Type
- Location
- Title
- Job Description
- Soft Skills
- Hard Skills
- Certificates
- How to Apply
- Export
